version: '3.1'
services:
  bookmedik:
    container_name: app_bookmedik
    image: alejandro/bookmedik:v1
    restart: always
    environment:
      BOOKMEDIK_USER: bookmedik
      BOOKMEDIK_PASS: bookmedik
      HOST_DB: mariadb_bookmedik
      NAME_DB: bookmedik
    ports:
      - 8085:80
    depends_on:
      - db
  db:
    container_name: mariadb_bookmedik
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: admin
      MARIADB_USER: admin
      MARIADB_PASSWORD: bookmedik
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
